craft-applications:
  - charmcraft
  - imagecraft
  - rockcraft
  - snapcraft
  - debcraft

craft-libraries:
  - craft-application
  - craft-archives
  # not used by any projects
  # - craft-artifacts
  - craft-cli
  - craft-grammar
  - craft-parts
  - craft-platforms
  - craft-providers
  - craft-store

craft-projects:
  - charmcraft
  - craft-application
  - craft-archives
  - craft-artifacts
  - craft-actions
  - craft-cli
  - craft-grammar
  - craft-parts
  - craft-platforms
  - craft-providers
  - craft-store
  - debcraft
  - imagecraft
  - rockcraft
  - snapcraft
  - snapcraft-rocks
  - starbase
  - starflow

# Number of days before refreshing issue data from GitHub
refresh-interval-days: 7

# Oldest hotfix branch to include per application, as "major.minor".
# Branches with a lower version are excluded.
hotfix-min-versions:
  charmcraft: "3.0"
  snapcraft: "8.0"
  rockcraft: "1.15"

launchpad-projects:
  - snapcraft

# GitHub usernames of project maintainers
maintainers:
  - alderic-coroir
  - bepri
  - cmatsuoka
  - Copilot
  - come-maiz
  - cjdcordeiro
  - cjp256
  - dariuszd21
  - dboddie
  - dependabot[bot]
  - facundobatista
  - jahn-junior
  - kyrofa
  - lengau
  - mattculler
  - medubelko
  - mr-cal
  - renovate[bot]
  - sergiusens
  - smethnani
  - steinbro
  - syu-w
  - tigarmo
  - upils
