name: update launchpad
on:
  schedule:
    - cron:  '5 3 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: collect data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./src/main.py launchpad snapcraft
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci: update snapcraft data"
