name: slow data collection
on:
  schedule:
    # run every 3 days
    - cron: "0 0 */3 * *"
  workflow_dispatch:
    inputs:
      enable_ssh_access:
        type: boolean
        description: "Enable ssh access"
        required: false
        default: false

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up uv with caching
        id: setup-uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
          enable-cache: true
          cache-suffix: ${{ steps.runner-info.outputs.cache-hash }}
          ignore-nothing-to-cache: true
      - name: install project
        run: |
          uv tool install .
      - name: Enable ssh access
        uses: mxschmitt/action-tmate@v3
        if: ${{ inputs.enable_ssh_access }}
        with:
          limit-access-to-actor: true
      - name: collect data
        env:
          STARCRAFT_GITHUB_TOKEN: ${{ secrets.STARCRAFT_GITHUB_TOKEN }}
        run: |
          starcraft-stats get-issues --verbosity=trace
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        if: github.event_name != 'pull_request'
        with:
          commit_message: "ci: fetch craft applications & libraries"
          commit_author: "github-actions <github-actions@users.no-reply.github.com>"
          commit_user_name: "github-actions"
          commit_user_email: "github-actions@users.no-reply.github.com"
